CI/CD 테스트24

diff --git a/.github/workflows/docker-ci-cd.yml b/.github/workflows/docker-ci-cd.yml
--- a/.github/workflows/docker-ci-cd.yml
+++ b/.github/workflows/docker-ci-cd.yml
@@ -12,6 +12,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
@@ -38,6 +39,15 @@ jobs:
     needs: build
 
     steps:
+      - name: Set environment variables
+        run: |
+          echo "REDIS_HOST=redis" >> $GITHUB_ENV
+          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
+          echo "AES_SECRET_KEY=${{ secrets.AES_SECRET_KEY }}" >> $GITHUB_ENV
+          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
+          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
+          echo "ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }}" >> $GITHUB_ENV  
+
       - name: EC2 서버에 배포 (SSH 접속)
         uses: appleboy/ssh-action@v0.1.7
         with:
@@ -46,20 +56,19 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
             # Docker Compose가 설치되어 있지 않으면 설치
-            sudo apt-get update
-            sudo apt-get install -y docker-compose
+            if ! command -v docker-compose &> /dev/null
+            then
+                echo "docker-compose could not be found, installing..."
+                sudo apt-get update
+                sudo apt-get install -y docker-compose
+            else
+                echo "docker-compose is already installed"
+            fi
 
             # CoinTrading 최신 이미지 풀
             docker stop cointrading
             docker rm -f cointrading || true
             docker pull ${{ secrets.DOCKER_USERNAME }}/cointrading:latest
-            # GITHUB_ENV 생성
-            echo "REDIS_HOST=redis" >> $GITHUB_ENV
-            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
-            echo "AES_SECRET_KEY=${{ secrets.AES_SECRET_KEY }}" >> $GITHUB_ENV
-            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
-            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
-            echo "ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }}" >> $GITHUB_ENV
 
             # Docker Compose 실행
             docker-compose down
